
name: Create Json

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
     - uses: schdck/create-env-json@v1
       id: create-env
       with:
        file-name: 'env.json'
        variable: 'Hello World'
